using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TaggedUnions;

[Generator(LanguageNames.CSharp)]
public sealed class TaggedUnionGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "TaggedUnions.TaggedUnionAttribute";
    private const string NoImplicitOperatorAttributeMetadataName =
        "TaggedUnions.NoImplicitOperatorAttribute";

    // FullyQualifiedFormat alone drops '?' nullable-reference-type annotations, including ones
    // nested inside generic type arguments (e.g. AnyBoxed<Foo?>). Emitting types without them
    // makes the generated declaration's nullability disagree with the actual annotated value
    // flowing into it, producing a bogus CS8619 warning at the call site. Adding the modifier
    // flag keeps the emitted text's nullability in sync with the real type.
    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions
                | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
        );

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace TaggedUnions
        {
            [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            internal sealed class TaggedUnionAttribute : System.Attribute
            {
            }

            /// <summary>
            /// Put on a tagged-union case to skip generating an implicit conversion operator for it.
            /// Required when the case's single constructor parameter is an interface type, since C#
            /// does not allow user-defined conversions to or from an interface; also usable if you
            /// simply don't want the implicit operator for a particular case.
            /// </summary>
            [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            internal sealed class NoImplicitOperatorAttribute : System.Attribute
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                "TaggedUnionAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)
            )
        );

        var unions = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                AttributeMetadataName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol
            )
            .Collect();

        context.RegisterSourceOutput(
            unions,
            static (spc, unions) =>
            {
                foreach (var union in unions)
                {
                    Generate(spc, union);
                }
            }
        );
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol union)
    {
        var unionSyntax = (ClassDeclarationSyntax)union.DeclaringSyntaxReferences[0].GetSyntax();

        if (union.TypeKind != TypeKind.Class)
        {
            context.ReportDiagnostic(
                Diagnostic.Create(Diagnostics.UnionMustBeClass, union.Locations[0], union.Name)
            );
            return;
        }

        if (!union.IsAbstract)
        {
            context.ReportDiagnostic(
                Diagnostic.Create(Diagnostics.UnionMustBeAbstract, union.Locations[0], union.Name)
            );
            return;
        }

        if (!unionSyntax.Modifiers.Any(SyntaxKind.PartialKeyword))
        {
            context.ReportDiagnostic(
                Diagnostic.Create(Diagnostics.UnionMustBePartial, union.Locations[0], union.Name)
            );
            return;
        }

        var cases = union
            .GetTypeMembers()
            .Where(t =>
                t.TypeKind == TypeKind.Class
                && SymbolEqualityComparer.Default.Equals(t.BaseType, union)
            )
            .ToImmutableArray();

        if (cases.IsEmpty)
        {
            context.ReportDiagnostic(
                Diagnostic.Create(Diagnostics.NoCasesFound, union.Locations[0], union.Name)
            );
            return;
        }

        var caseInfos = new List<CaseInfo>();
        var hasError = false;

        foreach (var @case in cases)
        {
            if (!@case.IsSealed)
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        Diagnostics.CaseMustBeSealed,
                        @case.Locations[0],
                        @case.Name,
                        union.Name
                    )
                );
                hasError = true;
                continue;
            }

            var publicCtors = @case
                .Constructors.Where(c =>
                    !c.IsStatic && c.DeclaredAccessibility == Accessibility.Public
                )
                .ToImmutableArray();

            if (publicCtors.Length != 1)
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        Diagnostics.CaseAmbiguousConstructor,
                        @case.Locations[0],
                        @case.Name,
                        union.Name,
                        publicCtors.Length
                    )
                );
                hasError = true;
                continue;
            }

            var ctor = publicCtors[0];
            var isPrimaryConstructor =
                ctor.DeclaringSyntaxReferences.Length > 0
                && ctor.DeclaringSyntaxReferences[0].GetSyntax() is ClassDeclarationSyntax;

            var noImplicitOperator = @case
                .GetAttributes()
                .Any(a =>
                    a.AttributeClass?.ToDisplayString() == NoImplicitOperatorAttributeMetadataName
                );

            caseInfos.Add(new CaseInfo(@case, ctor, isPrimaryConstructor, noImplicitOperator));
        }

        if (hasError)
        {
            return;
        }

        // A parameterless case has no wrapped value to convert from, so there is no implicit
        // operator to generate for it - silently skip rather than emitting a bogus operator
        // taking an empty tuple `()`, which is not valid C#.
        foreach (var caseInfo in caseInfos)
        {
            if (caseInfo.Constructor.Parameters.Length == 0)
            {
                caseInfo.SkipImplicitOperator = true;
            }
        }

        // An implicit operator can't convert to/from an interface type - skip (with a warning)
        // instead of emitting code that will fail to compile with CS0552.
        foreach (var caseInfo in caseInfos)
        {
            if (caseInfo.SkipImplicitOperator)
            {
                continue;
            }

            if (
                caseInfo.Constructor.Parameters.Length == 1
                && caseInfo.Constructor.Parameters[0].Type.TypeKind == TypeKind.Interface
            )
            {
                var p = caseInfo.Constructor.Parameters[0];
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        Diagnostics.ImplicitOperatorFromInterface,
                        caseInfo.Type.Locations[0],
                        caseInfo.Type.Name,
                        union.Name,
                        p.Type.ToDisplayString()
                    )
                );
                caseInfo.SkipImplicitOperator = true;
            }
        }

        // Detect colliding implicit-operator signatures.
        var seenSignatures = new Dictionary<string, CaseInfo>();
        foreach (var caseInfo in caseInfos)
        {
            if (caseInfo.SkipImplicitOperator)
            {
                continue;
            }

            var signature = string.Join(
                "|",
                caseInfo.Constructor.Parameters.Select(p =>
                    p.Type.ToDisplayString(TypeDisplayFormat)
                )
            );

            if (seenSignatures.TryGetValue(signature, out var existing))
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        Diagnostics.OperatorSignatureCollision,
                        caseInfo.Type.Locations[0],
                        existing.Type.Name,
                        caseInfo.Type.Name,
                        union.Name,
                        signature.Replace("|", ", ")
                    )
                );
                hasError = true;
                continue;
            }

            seenSignatures[signature] = caseInfo;
        }

        if (hasError)
        {
            return;
        }

        var source = GenerateSource(union, caseInfos);
        var namespacePrefix = union.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : union.ContainingNamespace.ToDisplayString().Replace('.', '_') + "_";
        var hintName = $"{namespacePrefix}{GetNestedName(union)}.g.cs";
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string GetNestedName(INamedTypeSymbol type)
    {
        var names = new Stack<string>();
        for (var t = type; t is not null; t = t.ContainingType)
        {
            names.Push(t.Name);
        }

        return string.Join("_", names);
    }

    private static string GenerateSource(INamedTypeSymbol union, List<CaseInfo> caseInfos)
    {
        var sb = new StringBuilder();
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();

        var hasNamespace = !union.ContainingNamespace.IsGlobalNamespace;
        if (hasNamespace)
        {
            _ = sb.AppendLine($"namespace {union.ContainingNamespace.ToDisplayString()}");
            _ = sb.AppendLine("{");
        }

        var containingTypes = new Stack<INamedTypeSymbol>();
        for (var t = union.ContainingType; t is not null; t = t.ContainingType)
        {
            containingTypes.Push(t);
        }

        foreach (var containingType in containingTypes)
        {
            _ = sb.AppendLine($"partial class {containingType.Name}");
            _ = sb.AppendLine("{");
        }

        _ = sb.AppendLine($"partial class {union.Name}");
        _ = sb.AppendLine("{");

        // Implicit conversion operators.
        foreach (var caseInfo in caseInfos)
        {
            if (caseInfo.SkipImplicitOperator)
            {
                continue;
            }

            AppendOperator(sb, union, caseInfo);
        }

        // Match / Switch helpers.
        AppendMatch(sb, union, caseInfos);
        AppendSwitch(sb, union, caseInfos);

        _ = sb.AppendLine("}"); // union

        foreach (var _ct in containingTypes)
        {
            _ = _ct;
            _ = sb.AppendLine("}");
        }

        if (hasNamespace)
        {
            _ = sb.AppendLine("}");
        }

        // Per-case generated property parts, for cases using the primary-constructor shorthand.
        foreach (var caseInfo in caseInfos)
        {
            if (!caseInfo.IsPrimaryConstructor)
            {
                continue;
            }

            AppendCaseProperties(sb, union, caseInfo, hasNamespace, containingTypes);
        }

        return sb.ToString();
    }

    private static void AppendOperator(StringBuilder sb, INamedTypeSymbol union, CaseInfo caseInfo)
    {
        var unionName = union.Name;
        var caseName = caseInfo.Type.Name;
        var parameters = caseInfo.Constructor.Parameters;

        if (parameters.Length == 1)
        {
            var p = parameters[0];
            var typeName = p.Type.ToDisplayString(TypeDisplayFormat);
            _ = sb.AppendLine(
                $"    public static implicit operator {unionName}({typeName} {p.Name})"
            );
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine($"        return new {caseName}({p.Name});");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
        }
        else
        {
            var tupleElements = string.Join(
                ", ",
                parameters.Select(p => $"{p.Type.ToDisplayString(TypeDisplayFormat)} {p.Name}")
            );
            var args = string.Join(", ", parameters.Select(p => $"pair.{p.Name}"));

            _ = sb.AppendLine(
                $"    public static implicit operator {unionName}(({tupleElements}) pair)"
            );
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine($"        return new {caseName}({args});");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
        }
    }

    private static void AppendMatch(
        StringBuilder sb,
        INamedTypeSymbol union,
        List<CaseInfo> caseInfos
    )
    {
        var typeParams = string.Join(
            ", ",
            caseInfos.Select(c => $"System.Func<{c.Type.Name}, TResult> {CamelCase(c.Type.Name)}")
        );
        _ = sb.AppendLine($"    public TResult Match<TResult>({typeParams})");
        _ = sb.AppendLine("    {");
        for (var i = 0; i < caseInfos.Count; i++)
        {
            var c = caseInfos[i];
            _ = sb.AppendLine(
                $"        if (this is {c.Type.Name} case{i}) return {CamelCase(c.Type.Name)}(case{i});"
            );
        }
        _ = sb.AppendLine(
            $"        throw new System.InvalidOperationException(\"Unreachable: unknown case of \" + nameof({union.Name}) + \".\");"
        );
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void AppendSwitch(
        StringBuilder sb,
        INamedTypeSymbol union,
        List<CaseInfo> caseInfos
    )
    {
        var parameters = string.Join(
            ", ",
            caseInfos.Select(c => $"System.Action<{c.Type.Name}> {CamelCase(c.Type.Name)}")
        );
        _ = sb.AppendLine($"    public void Switch({parameters})");
        _ = sb.AppendLine("    {");
        for (var i = 0; i < caseInfos.Count; i++)
        {
            var c = caseInfos[i];
            _ = sb.AppendLine(
                $"        if (this is {c.Type.Name} case{i}) {{ {CamelCase(c.Type.Name)}(case{i}); return; }}"
            );
        }
        _ = sb.AppendLine(
            $"        throw new System.InvalidOperationException(\"Unreachable: unknown case of \" + nameof({union.Name}) + \".\");"
        );
        _ = sb.AppendLine("    }");
    }

    private static void AppendCaseProperties(
        StringBuilder sb,
        INamedTypeSymbol union,
        CaseInfo caseInfo,
        bool hasNamespace,
        Stack<INamedTypeSymbol> containingTypes
    )
    {
        _ = sb.AppendLine();

        if (hasNamespace)
        {
            _ = sb.AppendLine($"namespace {union.ContainingNamespace.ToDisplayString()}");
            _ = sb.AppendLine("{");
        }

        foreach (var containingType in containingTypes)
        {
            _ = sb.AppendLine($"partial class {containingType.Name}");
            _ = sb.AppendLine("{");
        }

        _ = sb.AppendLine($"partial class {union.Name}");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine($"    partial class {caseInfo.Type.Name}");
        _ = sb.AppendLine("    {");

        var existingPropertyNames = new HashSet<string>(
            caseInfo.Type.GetMembers().OfType<IPropertySymbol>().Select(p => p.Name)
        );

        foreach (var p in caseInfo.Constructor.Parameters)
        {
            if (existingPropertyNames.Contains(p.Name))
            {
                continue;
            }

            var typeName = p.Type.ToDisplayString(TypeDisplayFormat);
            var needsNullCheck =
                p.Type.IsReferenceType && p.Type.NullableAnnotation != NullableAnnotation.Annotated;

            _ = needsNullCheck
                ? sb.AppendLine(
                    $"        public {typeName} {p.Name} {{ get; }} = {p.Name} ?? throw new System.ArgumentNullException(nameof({p.Name}));"
                )
                : sb.AppendLine($"        public {typeName} {p.Name} {{ get; }} = {p.Name};");
        }

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        foreach (var _ct in containingTypes)
        {
            _ = sb.AppendLine("}");
        }

        if (hasNamespace)
        {
            _ = sb.AppendLine("}");
        }
    }

    private static string CamelCase(string name) =>
        name.Length == 0 ? name
        : name.Length == 1 || name.All(char.IsUpper) ? name.ToLowerInvariant()
        : char.ToLowerInvariant(name[0]) + name.Substring(1);

    private sealed class CaseInfo(
        INamedTypeSymbol type,
        IMethodSymbol constructor,
        bool isPrimaryConstructor,
        bool skipImplicitOperator
    )
    {
        public INamedTypeSymbol Type { get; } = type;
        public IMethodSymbol Constructor { get; } = constructor;
        public bool IsPrimaryConstructor { get; } = isPrimaryConstructor;
        public bool SkipImplicitOperator { get; set; } = skipImplicitOperator;
    }
}
